### ISSUE TITLE
Segfault when running mappingPatrol

### ISSUE THREAD

**Issue by exwu** [h2r/ein#1]
Program received signal SIGSEGV, Segmentation fault.
0x0000000000e4a03d in goClassifyBlueBoxes (ms=...) at /home/emily/catkin_ws/src/ein/src/ein.cpp:11506
11506           label = ms->config.kNN->find_nearest(descriptors2, param_numNeighbors);

**Comment by stefie10** [comment]
Fixed, and also fixed error message problem, and also we don't use this stack any more.
