### ISSUE TITLE
Pick and Place Installation

### ISSUE THREAD

**Issue by agbala** [h2r/ein#11]
Hello,
I am attempting to install the ein pick and place program and have run into an error in the installation. Whenever I run catkin_make, as instructed, it reaches 70% when it runs into a few errors shown below:

[ 70%] Building CXX object ein/CMakeFiles/ein.dir/src/ein_scanning.cpp.o
/home/baxter/catkin_ws/src/ein/src/ein.cpp: In function ‘int getStreamPoseAtTime(MachineState*, double, eePose*, eePose*)’:
/home/baxter/catkin_ws/src/ein/src/ein.cpp:1478:126: error: a function-definition is not allowed here before ‘{’ token
 void castRangeRay(MachineState * ms, double thisRange, eePose thisPose, Vector3d * castPointOut, Vector3d * rayDirectionOut) {
                                                                                                                              ^
/home/baxter/catkin_ws/src/ein/src/ein.cpp:1507:63: error: a function-definition is not allowed here before ‘{’ token
 void update2dRangeMaps(MachineState * ms, Vector3d castPoint) {
                                                               ^
/home/baxter/catkin_ws/src/ein/src/ein.cpp:8425:29: error: expected ‘}’ before end of line
     #pragma omp parallel for
                             ^
/home/baxter/catkin_ws/src/ein/src/ein.cpp: At global scope:
/home/baxter/catkin_ws/src/ein/src/ein.cpp:8425:29: error: expected declaration before end of line
[ 70%] Building CXX object ein/CMakeFiles/ein.dir/src/ein_misc.cpp.o
cc1plus: warning: unrecognized command line option "-Wno-deprecated-register" [enabled by default]
make[2]: *** [ein/CMakeFiles/ein.dir/src/ein.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [ein/CMakeFiles/ein.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

I'm fairly new to C++, but I am pretty sure that everything after "cc1plus: warning: unrecognized command line option..." is what invokes "make -j8 -l8" and then stops the installation.
Please help!
Thanks.

**Comment by stefie10** [comment]
Hi we just pushed a fix for this problem, please pull and try again!
