### ISSUE TITLE
save the fence in the config

### ISSUE THREAD

**Issue by joberlin** [h2r/ein#3]
and allow the default fence to be quickly recovered

**Comment by stefie10** [comment]
We changed the workspace to use the robot's entire IK space.  There are also words to set the fence dynamically.    You can use mapSearchFence<tab> to read the variables, and setMapSearchFence<tab> to set their values.  If you change the fence values, you will need to rebuild the IK map.  See fillIkMapAtCurrentHeight and its friends.
