### ISSUE TITLE
File missing "ein/EinState.h" <ein/EinConsole.h> 

### ISSUE THREAD

**Issue by ZuyuanZhu** [h2r/ein#35]
fatal error: ein/EinState.h: No such file or directory #include "ein/EinState.h"
fatal error: ein/EinConsole.h: No such file or directory  #include <ein/EinConsole.h>

I can't find it with Google, please upload the files, or we can't continue the 'catkin_make'

Regards,
Zuyuan

**Comment by stefie10** [comment]
Hi, this is a problem with the build, as this file is generated via the ROS messages.  Make sure that it's generating messages, and try running catkin again.
