### ISSUE TITLE
Parsing doesn't handle negative exponents

### ISSUE THREAD

**Issue by joberlin** [h2r/ein#5]
Testing if symbol: 5.53848e-321
no symbol
Cannot parse 5.53848e-321
Warning, ignoring unknown word from the forth topic: 5.53848e-321

**Comment by stefie10** [comment]
This works for smaller exponents.  The problem is probably overflow.  Don't try such large or small numbers.

**Comment by stefie10** [comment]
I checked if stod could at least give a better error message, but it doesn't.  Possibly we should change to boost for parsing or something else... anyway not going to worry about this now.
